language: go
services:
  - postgresql
before_script:
  - psql -c 'create database baskets;' -U postgres
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
script:
  # - go test -v ./...
  - $HOME/gopath/bin/goveralls -v -service=travis-ci
