language: go
go:
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/stretchr/testify/assert
script:
  - go test -v ./...
  - $HOME/gopath/bin/goveralls -service=travis-ci
