############################################
# RESTful API for Request Baskets service
#
swagger: '2.0'

info:
  version: 0.3
  title: Request Baskets API
  description: RESTful API of Request Baskets service
  contact:
    name: darklynx
    url: https://github.com/darklynx

host: localhost:55555
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

# Groups and their descriptions
tags:
  - name: baskets
    description: Manage baskets
  - name: requests
    description: Manage collected requests

# Security (maybe use custom header, e.g. basket_key, basket_token)
securityDefinitions:
  basket_token:
    description: Basket assigned secure token
    type: apiKey
    name: Authorization
    in: header

# URL patterns
paths:
  /baskets:
    get:
      tags:
        - baskets
      summary: Retrieve registered basket names
      description: Returns list of registered basket names
      parameters:
        - name: max
          in: query
          type: integer
          description: Maximum number of basket names to return, default 20
          required: false
        - name: skip
          in: query
          type: integer
          description: Number of basket names to skip, default 0
          required: false
      responses:
        200:
          description: OK. Returns list of available baskets.
          schema:
            $ref: '#/definitions/Baskets'
        204:
          description: No Content. No baskets available for specified limits

  /baskets/{basket-name}:
    post:
      tags:
        - baskets
      summary: Create a new basket
      description: Allows to create a new basket with specified name
      parameters:
        - name: basket-name
          in: path
          type: string
          description: The name of basket to create
          required: true
        - name: config
          in: body
          description: Basket configuration
          required: false
          schema:
            $ref: '#/definitions/Config'
      responses:
        201:
          description: Created. Indicates that basket is successfully created
          schema:
            $ref: '#/definitions/Token'
        409:
          description: Conflict. Indicates that basket with such name already exists
        403:
          description: Forbidden. Indicates that basket name conflicts with reserved paths; e.g. `baskets`, `web`, etc.
    get:
      tags:
        - baskets
      summary: Get basket configuration
      description: Get current configuration of a basket
      parameters:
        - name: basket-name
          in: path
          type: string
          description: The basket name
          required: true
      responses:
        200:
          description: OK. Returns basket configuration
          schema:
            $ref: '#/definitions/Config'
        401:
          description: Unauthorized. Invalid or missing basket token
        404:
          description: Not Found. No basket with such name
      security:
        - basket_token: []
    put:
      tags:
        - baskets
      summary: Update basket configuration
      description: Update current configuration of basket
      parameters:
        - name: basket-name
          in: path
          type: string
          description: The basket name
          required: true
        - name: config
          in: body
          description: New configuration to apply
          required: true
          schema:
            $ref: '#/definitions/Config'
      responses:
        204:
          description: No Content. Basket configuration is updated
        401:
          description: Unauthorized. Invalid or missing basket token
        404:
          description: Not Found. No basket with such name
      security:
        - basket_token: []
    delete:
      tags:
        - baskets
      summary: Delete basket
      description: Delete basket and all collected requests
      parameters:
        - name: basket-name
          in: path
          type: string
          description: The basket name
          required: true
      responses:
        204:
          description: No Content. Basket is deleted
        401:
          description: Unauthorized. Invalid or missing basket token
        404:
          description: Not Found. No basket with such name
      security:
        - basket_token: []

  /baskets/{basket-name}/requests:
    get:
      tags:
        - requests
      summary: Retrieve requests collected by basket
      description: Returns list of collected requests
      parameters:
        - name: max
          in: query
          type: integer
          description: Maximum number of requests to return, default 20
          required: false
        - name: skip
          in: query
          type: integer
          description: Number of requests to skip, default 0
          required: false
      responses:
        200:
          description: OK. Returns list of basket requests.
          schema:
            $ref: '#/definitions/Requests'
        204:
          description: No Content. No requests found for specified limits
        401:
          description: Unauthorized. Invalid or missing basket token
        404:
          description: Not Found. No basket with such name
      security:
        - basket_token: []
    delete:
      tags:
        - requests
      summary: Delete all requests
      description: Clear all requests collected by this basket so far
      parameters:
        - name: basket-name
          in: path
          type: string
          description: The basket name
          required: true
      responses:
        204:
          description: No Content. Basket requests are cleared
        401:
          description: Unauthorized. Invalid or missing basket token
        404:
          description: Not Found. No basket with such name
      security:
        - basket_token: []

# Model
definitions:
  Baskets:
    type: object
    required:
      - names
      - count
      - has_more
    properties:
      names:
        type: array
        description: Collection of basket names
        items:
          type: string
      count:
        type: integer
        description: Total number of baskets in the system
      has_more:
        type: boolean
        description: Indicates if there are more baskets to fetch

  Config:
    type: object
    properties:
      forward_url:
        type: string
        description: URL to forward all incoming requests of the basket, `empty` value disables forwarding
      insecure_tls:
        type: boolean
        description: |
          If set to `true` the sertificate verification will be disabled if forward URL indicates HTTPS scheme.
          This allows to forward collected HTTP requests via HTTPS protocol even if the forward end-point is configured
          with self-signed TLS/SSL certificate. **Warning:** enabling this feature has known security implications.
      expand_path:
        type: boolean
        description: |
          If set to `true` the forward URL path will be expanded if original HTTP request contains compound path.
          For example, a basket with name `collector` is configured to forward all requests to URL
          `http://my.internal.service/listener` and it has received an HTTP GET request like
          `GET http://baskets.example.com/collector/company/12/users?action=find&name=John`.
          Depending on `expand_path` settings the request will be forwarded as following:
          `true` => `GET http://my.internal.service/listener/company/12/users?action=find&name=John`,
          `false` => `GET http://my.internal.service/listener?action=find&name=John`
      capacity:
        type: integer
        description: Baskets capacity, defines maximum number of requests to store

  Token:
    type: object
    required:
      - token
    properties:
      token:
        type: string
        description: Secure token to manage the basket, generated by system

  Requests:
    type: object
    required:
      - requests
      - count
      - total_count
      - has_more
    properties:
      requests:
        type: array
        description: Collection of collected requests
        items:
          $ref: '#/definitions/Request'
      count:
        type: integer
        description: Current number of collected requests hold by basket
      total_count:
        type: integer
        description: Total number of all requests passed through this basket
      has_more:
        type: boolean
        description: Indicates if there are more requests collected by basket to fetch

  Request:
    type: object
    properties:
      date:
        type: integer
        format: int64
        description: Date and time of request in Unix time ms. format (number of miliseconds elapsed since January 1, 1970 UTC)
      headers:
        $ref: '#/definitions/Headers'
        description: Map of request headers, key represents name, value is array of values
      content_length:
        type: integer
        description: Content lenght of request
      body:
        type: string
        description: Content of request body
      method:
        type: string
        description: HTTP methof of request
      path:
        type: string
        description: URL path of request
      query:
        type: string
        description: Query parameters of request

  Headers:
    type: object
    additionalProperties:
      type: array
      description: Collection of header values
      items:
        type: string
